[package]
name = "uart-service"
version = "0.1.0"
edition = "2024"
description = "UART embedded service implementation"
repository = "https://github.com/OpenDevicePartnership/embedded-services"
rust-version = "1.88"
license = "MIT"

[lints]
workspace = true

[dependencies]
bitfield.workspace = true
embedded-services.workspace = true
defmt = { workspace = true, optional = true }
log = { workspace = true, optional = true }
embassy-time.workspace = true
embassy-sync.workspace = true
embassy-futures.workspace = true
mctp-rs = { workspace = true }
embedded-io-async.workspace = true
num_enum.workspace = true

# TODO Service message type crates are a temporary dependency until we can parameterize
#      the supported messages types at UART service creation time.
battery-service-messages.workspace = true
debug-service-messages.workspace = true
thermal-service-messages.workspace = true

[features]
default = []
defmt = [
    "dep:defmt",
    "embedded-services/defmt",
    "embassy-time/defmt",
    "embassy-time/defmt-timestamp-uptime",
    "embassy-sync/defmt",
    "mctp-rs/defmt",
    "thermal-service-messages/defmt",
    "battery-service-messages/defmt",
    "debug-service-messages/defmt",
]

log = ["dep:log", "embedded-services/log", "embassy-time/log"]
