
# cargo-vet audits file

[[audits.addr2line]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.24.2"

[[audits.aligned]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.4.2"

[[audits.aquamarine]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.6.0"

[[audits.as-slice]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.1"

[[audits.backtrace]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.3.75"

[[audits.block-device-driver]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.0"

[[audits.embedded-batteries]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0"
notes = "ODP crates are always trusted."

[[audits.embedded-batteries]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0@git:410e2482d54b58c205a425c70d2ccf062e3ee3f3"
importable = false
notes = "ODP crates are always trusted."

[[audits.embedded-batteries]]
who = "Matteo Tullo <matteotullo@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.0"
notes = "ODP crates are always trusted."

[[audits.embedded-batteries]]
who = "Matteo Tullo <matteotullo@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.1"
notes = "ODP crates are always trusted."

[[audits.embedded-batteries-async]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0"
notes = "ODP crates are always trusted."

[[audits.embedded-batteries-async]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0@git:410e2482d54b58c205a425c70d2ccf062e3ee3f3"
importable = false
notes = "ODP crates are always trusted."

[[audits.embedded-batteries-async]]
who = "Matteo Tullo <matteotullo@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.0"
notes = "ODP crates are always trusted."

[[audits.embedded-batteries-async]]
who = "Matteo Tullo <matteotullo@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.1"

[[audits.embedded-fans]]
who = "Kurtis Dinelle <kdinelle@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0"
notes = "ODP crates are always trusted."

[[audits.embedded-fans-async]]
who = "Kurtis Dinelle <kdinelle@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.0"
notes = "ODP crates are always trusted."

[[audits.embedded-sensors-hal]]
who = "Kurtis Dinelle <kdinelle@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0"
notes = "ODP crates are always trusted."

[[audits.embedded-sensors-hal-async]]
who = "Kurtis Dinelle <kdinelle@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.3.0"
notes = "ODP crates are always trusted."

[[audits.gimli]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.31.1"

[[audits.half]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
delta = "2.5.0 -> 2.6.0"
notes = "Big change seems to be a change in the repo URL, but both the old and new URL resolve to the same place so it looks like the author is still in control."

[[audits.include_dir]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.7.4"

[[audits.include_dir_macros]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.7.4"

[[audits.indexmap]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "2.9.0"

[[audits.itertools]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.10.5"

[[audits.itertools]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.11.0"
notes = "Used as a dependency for embassy-imxrt."

[[audits.libc]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.2.172"

[[audits.memchr]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "2.7.4"

[[audits.mimxrt633s-pac]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.4.0"

[[audits.mimxrt633s-pac]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.4.1"

[[audits.miniz_oxide]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.8.8"

[[audits.object]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.36.7"

[[audits.portable-atomic]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.11.1"

[[audits.portable-atomic]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "1.11.1"

[[audits.serde_spanned]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.6.8"

[[audits.static_cell]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "2.1.1"

[[audits.static_cell]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "2.1.1"

[[audits.tokio]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "1.45.0"

[[audits.tokio-macros]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "2.5.0"

[[audits.toml]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.8.22"

[[audits.toml_datetime]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.6.9"

[[audits.toml_edit]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.22.26"

[[audits.uuid]]
who = "Jerry Xie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.17.0"

[[audits.windows-targets]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.windows_aarch64_gnullvm]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.windows_aarch64_msvc]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.windows_i686_gnu]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.0"

[[audits.windows_i686_gnu]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.windows_i686_gnullvm]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.windows_i686_msvc]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.windows_x86_64_gnu]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.windows_x86_64_gnullvm]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.windows_x86_64_msvc]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-run"
version = "0.52.6"

[[audits.winnow]]
who = "jerrysxie <jerryxie@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.7.10"

[[audits.zerocopy]]
who = "Matteo Tullo <matteotullo@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.8.26"

[[audits.zerocopy-derive]]
who = "Matteo Tullo <matteotullo@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.8.26"

[[trusted.anyhow]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-05"
end = "2026-04-16"
