
# cargo-vet audits file

[[audits.embedded-batteries]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0"
notes = "ODP crates are always trusted."

[[audits.embedded-batteries]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0@git:410e2482d54b58c205a425c70d2ccf062e3ee3f3"
importable = false
notes = "ODP crates are always trusted."

[[audits.embedded-batteries-async]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0"
notes = "ODP crates are always trusted."

[[audits.embedded-batteries-async]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.0@git:410e2482d54b58c205a425c70d2ccf062e3ee3f3"
importable = false
notes = "ODP crates are always trusted."

[[audits.half]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
delta = "2.5.0 -> 2.6.0"
notes = "Big change seems to be a change in the repo URL, but both the old and new URL resolve to the same place so it looks like the author is still in control."

[[audits.itertools]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.11.0"
notes = "Used as a dependency for embassy-imxrt."

[[audits.mimxrt633s-pac]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.4.0"

[[audits.mimxrt633s-pac]]
who = "Robert Zieba <robertzieba@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.4.1"

[[trusted.anyhow]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-05"
end = "2026-04-16"
