
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.OpenDevicePartnership]
url = "https://raw.githubusercontent.com/OpenDevicePartnership/rust-crate-audits/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.embassy-imxrt]
audit-as-crates-io = false

[[exemptions.adler2]]
version = "2.0.1"
criteria = "safe-to-run"

[[exemptions.ahash]]
version = "0.8.12"
criteria = "safe-to-deploy"

[[exemptions.askama]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.askama_derive]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.askama_parser]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.atomic-polyfill]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.az]]
version = "1.2.1"
criteria = "safe-to-deploy"

[[exemptions.bare-metal]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.bincode]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.bincode_derive]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.bitfield]]
version = "0.13.2"
criteria = "safe-to-deploy"

[[exemptions.bitfield]]
version = "0.15.0"
criteria = "safe-to-deploy"

[[exemptions.bitfield]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.bitfield]]
version = "0.19.2"
criteria = "safe-to-deploy"

[[exemptions.bitfield-macros]]
version = "0.19.2"
criteria = "safe-to-deploy"

[[exemptions.bitfield-struct]]
version = "0.10.1"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.9.4"
criteria = "safe-to-deploy"

[[exemptions.bitvec]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.bytemuck]]
version = "1.23.2"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.40"
criteria = "safe-to-deploy"

[[exemptions.cobs]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.convert_case]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.cortex-m]]
version = "0.7.7"
criteria = "safe-to-deploy"

[[exemptions.cortex-m-rt]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.cortex-m-rt-macros]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.crc]]
version = "3.3.0"
criteria = "safe-to-deploy"

[[exemptions.crc-catalog]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.critical-section]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.crunchy]]
version = "0.2.4"
criteria = "safe-to-deploy"

[[exemptions.darling]]
version = "0.20.11"
criteria = "safe-to-deploy"

[[exemptions.darling_core]]
version = "0.20.11"
criteria = "safe-to-deploy"

[[exemptions.darling_macro]]
version = "0.20.11"
criteria = "safe-to-deploy"

[[exemptions.dd-manifest-tree]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.defmt]]
version = "0.3.100"
criteria = "safe-to-deploy"

[[exemptions.defmt]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.defmt-macros]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.defmt-parser]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.device-driver]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.device-driver-generation]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.device-driver-macros]]
version = "1.0.7"
criteria = "safe-to-deploy"

[[exemptions.embassy-embedded-hal]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.embassy-executor]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.embassy-executor-macros]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.embassy-executor-timer-queue]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.embassy-futures]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.embassy-hal-internal]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.embassy-sync]]
version = "0.7.2"
criteria = "safe-to-deploy"

[[exemptions.embassy-time]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.embassy-time-driver]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.embassy-time-queue-utils]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal-async]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-hal-nb]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.embedded-io]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.embedded-io-async]]
version = "0.6.1"
criteria = "safe-to-deploy"

[[exemptions.embedded-storage]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.embedded-storage-async]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.fixed]]
version = "1.29.0"
criteria = "safe-to-deploy"

[[exemptions.funty]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.hash32]]
version = "0.2.1"
criteria = "safe-to-deploy"

[[exemptions.hash32]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.14.5"
criteria = "safe-to-deploy"

[[exemptions.hashbrown]]
version = "0.15.5"
criteria = "safe-to-deploy"

[[exemptions.hashlink]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.heapless]]
version = "0.7.17"
criteria = "safe-to-deploy"

[[exemptions.heapless]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.ident_case]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.indexmap]]
version = "2.11.0"
criteria = "safe-to-deploy"

[[exemptions.io-uring]]
version = "0.7.10"
criteria = "safe-to-run"

[[exemptions.itertools]]
version = "0.14.0"
criteria = "safe-to-deploy"

[[exemptions.kdl]]
version = "6.3.4"
criteria = "safe-to-deploy"

[[exemptions.libc]]
version = "0.2.175"
criteria = "safe-to-run"

[[exemptions.litrs]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.13"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.28"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.5"
criteria = "safe-to-deploy"

[[exemptions.miette]]
version = "7.6.0"
criteria = "safe-to-deploy"

[[exemptions.miette-derive]]
version = "7.6.0"
criteria = "safe-to-deploy"

[[exemptions.mimxrt600-fcb]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.mimxrt685s-pac]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.8.9"
criteria = "safe-to-run"

[[exemptions.mio]]
version = "1.0.4"
criteria = "safe-to-run"

[[exemptions.num]]
version = "0.4.3"
criteria = "safe-to-deploy"

[[exemptions.num-bigint]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.num-complex]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.num-iter]]
version = "0.1.45"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.paste]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.3.2"
criteria = "safe-to-deploy"

[[exemptions.postcard]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error-attr2]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.proc-macro-error2]]
version = "2.0.1"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.101"
criteria = "safe-to-deploy"

[[exemptions.radium]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.26"
criteria = "safe-to-run"

[[exemptions.rustc_version]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.rustc_version]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.20"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.semver]]
version = "1.0.26"
criteria = "safe-to-deploy"

[[exemptions.semver-parser]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.serde_json]]
version = "1.0.143"
criteria = "safe-to-deploy"

[[exemptions.serde_spanned]]
version = "0.6.9"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.11"
criteria = "safe-to-run"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.106"
criteria = "safe-to-deploy"

[[exemptions.tap]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.43"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.16"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.43"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.16"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.47.1"
criteria = "safe-to-run"

[[exemptions.toml]]
version = "0.8.23"
criteria = "safe-to-deploy"

[[exemptions.toml_datetime]]
version = "0.6.11"
criteria = "safe-to-deploy"

[[exemptions.toml_edit]]
version = "0.22.27"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.unty]]
version = "0.0.4"
criteria = "safe-to-deploy"

[[exemptions.vcell]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.virtue]]
version = "0.0.18"
criteria = "safe-to-deploy"

[[exemptions.volatile-register]]
version = "0.2.2"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.1+wasi-snapshot-preview1"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-run"

[[exemptions.winnow]]
version = "0.6.24"
criteria = "safe-to-deploy"

[[exemptions.winnow]]
version = "0.7.13"
criteria = "safe-to-deploy"

[[exemptions.wyz]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.yaml-rust2]]
version = "0.9.0"
criteria = "safe-to-deploy"
