# This workflow runs whenever a PR is opened or updated, or a commit is pushed to main. It runs
# several checks:
# - fmt: checks that the code is formatted according to rustfmt
# - semver: checks that the crate is following proper semantic versioning
# - doc: checks that the code can be documented without errors
# - hack: check combinations of feature flags for errors (including clippy warnings)
# - deny: checks licenses, advisories, sources, and bans for our dependencies
# - test: checks that unit tests pass and do not contain clippy warnings
# - msrv: check that the msrv specified in the crate is correct
# - clippy-arm-examples: checks that ARM examples contain no clippy warnings
# - clippy-std-examples: checks that std examples contain no clippy warnings
permissions:
  contents: read
# This configuration allows maintainers of this repo to create a branch and pull request based on
# the new branch. Restricting the push trigger to the main branch ensures that the PR only gets
# built once.
on:
  push:
    branches: [main]
  pull_request:
  workflow_call:
    inputs:
      download-lockfiles:
        required: false
        type: boolean
        default: false
# If new code is pushed to a PR branch, then cancel in progress workflows for that PR. Ensures that
# we don't waste CI time, and returns results quicker https://github.com/jonhoo/rust-ci-conf/pull/5
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: check
jobs:

  fmt:
    runs-on: ubuntu-latest
    name: stable / fmt
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: cargo fmt --check
        run: cargo fmt --check

  # Enable once we have a released crate
  # semver:
  #   runs-on: ubuntu-latest
  #   name: semver
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: true
  #     - name: Install stable
  #       uses: dtolnay/rust-toolchain@stable
  #       with:
  #         components: rustfmt
  #     - name: cargo-semver-checks
  #       uses: obi1kenobi/cargo-semver-checks-action@v2

  doc:
    # run docs generation on nightly rather than stable. This enables features like
    # https://doc.rust-lang.org/beta/unstable-book/language-features/doc-cfg.html which allows an
    # API be documented as only available in some specific platforms.
    runs-on: ubuntu-latest
    name: nightly / doc
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install nightly
        uses: dtolnay/rust-toolchain@nightly
      - name: cargo doc
        run: |
          cargo doc --no-deps -F log --locked
          cargo doc --no-deps -F defmt --locked
        env:
          RUSTDOCFLAGS: --cfg docsrs

  hack-clippy:
    # cargo-hack checks combinations of feature flags to ensure that features are all additive
    # which is required for feature unification
    # additionally, replacing `check` with `clippy` ensures all combinations of features generate no clippy warnings
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / ${{ matrix.target }} / clippy
    strategy:
      fail-fast: false
      matrix:
        # Get early warning of new lints which are regularly introduced in beta channels.
        toolchain: [stable, beta]
        target: [x86_64-unknown-linux-gnu, thumbv8m.main-none-eabihf]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy
      - name: cargo install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      - name: Download Cargo.lock files
        if: ${{ inputs.download-lockfiles }}
        uses: actions/download-artifact@v4
        with:
          name: updated-lock-files
      # intentionally no target specifier; see https://github.com/jonhoo/rust-ci-conf/pull/4
      # --feature-powerset runs for every combination of features
      - name: cargo hack
        run: cargo hack --feature-powerset --mutually-exclusive-features=log,defmt,defmt-timestamp-uptime clippy --locked --target ${{ matrix.target }}

  deny:
    # cargo-deny checks licenses, advisories, sources, and bans for
    # our dependencies.
    runs-on: ubuntu-latest
    name: ubuntu / stable / deny
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Download Cargo.lock files
        if: ${{ inputs.download-lockfiles }}
        uses: actions/download-artifact@v4
        with:
          name: updated-lock-files
      - name: cargo install cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          log-level: warn
          command: check
          arguments: --all-features --locked

  test:
    runs-on: ubuntu-latest
    name: ubuntu / stable / test
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Download Cargo.lock files
        if: ${{ inputs.download-lockfiles }}
        uses: actions/download-artifact@v4
        with:
          name: updated-lock-files
      - name: cargo test
        run: cargo test --locked
        # After ensuring tests pass, finally ensure the test code itself contains no clippy warnings
      - name: cargo clippy
        run: |
          cargo clippy --locked --tests

  msrv:
    # check that we can build using the minimal rust version that is specified by this crate
    runs-on: ubuntu-latest
    # we use a matrix here just because env can't be used in job names
    # https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
    strategy:
      fail-fast: false
      matrix:
        msrv: ["1.88"]
        target: [x86_64-unknown-linux-gnu, thumbv8m.main-none-eabihf]
    name: ubuntu / ${{ matrix.msrv }} / ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.msrv }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.msrv }}
      - name: Download Cargo.lock files
        if: ${{ inputs.download-lockfiles }}
        uses: actions/download-artifact@v4
        with:
          name: updated-lock-files
      - name: cargo +${{ matrix.msrv }} check
        run: |
          cargo check -F log --locked --target ${{ matrix.target }}
          cargo check -F defmt --locked --target ${{ matrix.target }}

  check-arm-examples:
    runs-on: ubuntu-latest
    # we use a matrix here just because env can't be used in job names
    # https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
    strategy:
      fail-fast: false
      matrix:
        example_directory: ["examples/rt633", "examples/rt685s-evk"]
    name: ubuntu / check-examples
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Download Cargo.lock files
        if: ${{ inputs.download-lockfiles }}
        uses: actions/download-artifact@v4
        with:
          name: updated-lock-files
      - name: cargo clippy
        working-directory: ${{ matrix.example_directory }}
        run: |
          cargo clippy --target thumbv8m.main-none-eabihf --locked

  check-std-examples:
    runs-on: ubuntu-latest
    # we use a matrix here just because env can't be used in job names
    # https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
    strategy:
      fail-fast: false
      matrix:
        example_directory: ["examples/std"]
    name: ubuntu / check-examples
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: Download Cargo.lock files
        if: ${{ inputs.download-lockfiles }}
        uses: actions/download-artifact@v4
        with:
          name: updated-lock-files
      - name: cargo clippy
        working-directory: ${{ matrix.example_directory }}
        run: |
          cargo clippy --locked
