# This workflow runs every morning at midnight. It will run cargo hack
# and a build with msrv. If any dependency breaks our crate, we will
# know ASAP.
#
# - hack: cargo hack for all workspace packages
# - msrv: check that the msrv specified in the crate is correct
# - check-*-examples: ensures examples still compile
permissions:
  contents: read

on:
  schedule:
    - cron: '0 0 * * *'

name: rolling
jobs:

  hack:
    # cargo-hack checks combinations of feature flags to ensure that features are all additive
    # which is required for feature unification
    runs-on: ubuntu-latest
    name: ubuntu / stable / features
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: cargo install cargo-hack
        uses: taiki-e/install-action@cargo-hack
      # intentionally no target specifier; see https://github.com/jonhoo/rust-ci-conf/pull/4
      # --feature-powerset runs for every combination of features
      - name: cargo hack
        run: |
          cargo update
          cargo hack --feature-powerset --mutually-exclusive-features=log,defmt check

  msrv:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        msrv: ["1.85"]
    name: ubuntu / ${{ matrix.msrv }} (${{ matrix.commit }})
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.msrv }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.msrv }}
      - name: cargo +${{ matrix.msrv }} check
        run: |
          cargo update
          cargo check -F log --locked
          cargo check -F defmt --locked

  check-arm-examples:
    runs-on: ubuntu-latest
    # we use a matrix here just because env can't be used in job names
    # https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
    strategy:
      fail-fast: false
      matrix:
        example_directory: ["examples/rt633", "examples/rt685s-evk"]
    name: ubuntu / check-examples
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: cargo check
        working-directory: ${{ matrix.example_directory }}
        run: |
          cargo update
          cargo check --target thumbv8m.main-none-eabihf

  check-std-examples:
    runs-on: ubuntu-latest
    # we use a matrix here just because env can't be used in job names
    # https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability
    strategy:
      fail-fast: false
      matrix:
        example_directory: ["examples/std"]
    name: ubuntu / check-examples
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: cargo check
        working-directory: ${{ matrix.example_directory }}
        run: |
          cargo update
          cargo check
